# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

eval "$(starship init bash)"

function drm() {
  # docker stop <container> && docker rm <container>
  if [ -z "$1" ]; then
    echo "Usage: drm <container_name> | <container_id>"
    return 1
  fi

  docker stop "$1" && docker rm "$1"
}

function dpsf() {
  # listing all running containers vertically
  format="ID\t{{.ID}}\nNAME\t{{.Names}}\nIMAGE\t{{.Image}}\nPORTS\t{{.Ports}}\nCOMMAND\t{{.Command}}\nCREATED\t{{.CreatedAt}}\nSTATUS\t{{.Status}}\n"
  docker ps --format=$format
}
